### ISSUE TITLE
请教一下这个的使用方法

### ISSUE THREAD

**Issue by ITdesk01** [hanwckf/openwrt-mt7615#1]
请教一下大佬这个要如何在openwrt正常加载

**Comment by hanwckf** [comment]
这个编译出来只有kmod，还需要配置脚本和相应的luci界面，比较麻烦...

**Comment by ITdesk01** [comment]
那再请教一个问题，如何使用你的文件，如：将这几个copy到openwrt某个目录里面，然后执行make menuconfig 的时候可以找到，luci的事情先不理吧，谢谢

**Comment by hanwckf** [comment]
这个的编译方法和其他openwrt软件包是一样的，目前仅在openwrt-18.06.1的源码里测试过能正常使用，其他没试
